vacation_mode:
  name: "vacation mode"
  description: "Switch control for vacation mode"
  target:
    entity:
      integration: culligan
      domain: switch

bypass_mode:
  name: "permanent bypass"
  description: "Switch control for permanent bypass"
  target:
    entity:
      integration: culligan
      domain: switch